# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publishDate', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField()),
            ],
        ),
    ]
